version: '3'

services:
  postgres:
    image: postgres
    ports:
      - '54320:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: yitan-blog
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
